### ISSUE TITLE
extend + nesting 

### ISSUE THREAD

**Issue by PixPunch** [davidtheclark/postcss-simple-extend#4]
Hello. Is possible to use next extend with nesting somehow?

**placeholder**

```
@define-placeholder hideText{
    text-indent: 110%;
    white-space: nowrap;
    overflow: hidden;
}
```

**source code** 

```
.foo {
    color: red;    
    .bar{
      @extend hideText;
    }
}
```

**compiled result** 

```
.foo {
    color: red
}
.foo .bar{ }
.bar{
    text-indent: 110%;
    white-space: nowrap;
    overflow: hidden;
}
```

**wanted result** 

```
.foo {
    color: red
}
.foo .bar{
    text-indent: 110%;
    white-space: nowrap;
    overflow: hidden;
}
```

**my postcss config** 

```
postcss([
  importer(),
  mixin(),
  simplevars,
  simpleExtend(),
  nestedcss,                    
  calc(),
  .......
```

Also you can try nesting before simple extend but results are predictable :)
only

```
.foo {
    color: red
}
```

will be compiled.

Thank you.

**Comment by davidtheclark** [comment]
I believe this is a problem with postcss-nested, not this plugin. See https://github.com/postcss/postcss-nested/issues/11
