### ISSUE TITLE
Ability to extend existing selectors

### ISSUE THREAD

**Issue by timkelty** [davidtheclark/postcss-simple-extend#6]
It would be great if we had the ability to also extend existing selectors (similar to how you can in Sass):
My use case for this is when you can't always restructure your code to have everything extending an initial `@define`, like when you want to extend a class from a library:

```
@import 'suitcss-utils'; // contains .u-cf...

.SomeClass {
  color: red;
}
.List--plain {
  @extend .u-cf;
  @extend .SomeClass;
}
```

**Comment by timkelty** [comment]
I just read the README, and it seems this is intentional :)

However, I'll leave this open if you have any specific thoughts on my use case.

**Comment by davidtheclark** [comment]
I will leave this open because it's a possibility worth considering. Your use-case makes sense, of course, as an argument in favor of adding this functionality.

Open to pull requests; and at some point I'll try to sit down myself and work on it.

**Comment by timkelty** [comment]
Sounds good.

**Comment by davidtheclark** [comment]
A hurdle: If we build in the functionality to extend regular selectors, this is no longer postcss-_simple_-extend: it's not _simple_ anymore. Would it make sense to rename the plugin? If so --- what's a good name, since postcss-extend is already taken?

**Comment by timkelty** [comment]
Good point.

You _could_ use NPM's shiny new scopes: http://blog.npmjs.org/post/116936804365/solving-npms-hard-problem-naming-packages

Or, just brainstorming:
`postcss-at-extend`
`postcss-extend-rule`
`postcss-extend-selector`
`postcss-selector-extend`

**Comment by timkelty** [comment]
Just a note: the more I'm getting into PostCSS the more I'm wanting a full-featured @extend.
I agree it's use is not without caveats, but those can really be managed with responsible use.

So, I'm excited to hear you're open to it. If I get some time, I may try to dig in.

**Comment by timkelty** [comment]
I think there is still a step that could be take to make `postcss-simple-extend` cover my use-case, without getting into the complexities [mentioned here](https://github.com/postcss/postcss/issues/321) in a full-featured extend.

For example, "simple" could refer to the fact that you're limited to extending simple selectors, e.g.

```
.foo {
  display: block;
}
.foo a {
  color: red;
}
.bar {
  @extend .foo;
  background: blue;
}
```

Would expand to:

```
.foo,
.bar {
  display: block;
}
.foo a,
.bar a {
  color: red;
}
.bar {
    background: blue;
}
```

However, the following would be disallowed. Sass allows you to do this, but it seems like way more trouble than it's worth:

```
.bar {
  @extend .foo a;
  background: blue;
}
```

Likewise, you could do the following, but `.foo a` would have no bearing on `@extend a`. (Sass's @extend would):

```
a {
  color: red;
}
.foo a {
  color: blue;
}
.bar {
  @extend a;
}
```

Expands to:

```
a,
.bar {
  color: red;
}
.foo a {
  color: blue;
}
.bar {
}
```

### Media query example

Since Media query rules cannont be combined, this either needs to be disallowed, or ideally duplicated only once per media scope:

```
.foo {
  content: 'foo';
}

@media (min-width: 500px){
  .bar {
    @extend .foo;
  }
  .baz {
    @extend .foo;
  }
}
```

Expands to:

```
.foo {
  content: 'foo';
}

@media (min-width: 500px){
  .bar,
  .baz {
    content: 'foo';
  }
}
```

**Comment by davidtheclark** [comment]
I think those are still some not-insignificant complications. Not as complicated as Sass's extend, you're right, but pretty significant nonetheless. I'm open to looking at a PR (can't guarantee I'll merge it, though, depending on how much complication it adds), but might no get to it myself for a little while.

**Comment by simonsmith** [comment]
Good article here by Philip Walton - http://philipwalton.com/articles/extending-styles/

Feel like that's a really nice use case for a full featured extend

**Comment by davidtheclark** [comment]
Thanks @simonsmith. Sorry if I miscommunicated -- I'm not at all _opposed_ to a full-featured extend. I just don't have the time to build it right now; and until it's built the simple-extend is serving my needs. If anybody else wants to get started on that full extend, I'll be happy to pitch in at some point.

**Comment by davidtheclark** [comment]
After looking at https://tech.bellycard.com/blog/sass-mixins-vs-extends-the-data/ I'm wondering if extending selectors from libraries is in fact the _only_ reason to use extends ...

**Comment by timkelty** [comment]
@davidtheclark interesting!

Whether or not the `extend` extends selectors or merely duplicated properties like a `mixin`, I still think an example like this is valid:

```
.PromoButton {
  @extend .Button;
  @extend .Header-item;
  /* Optional additional styles... */
}
```

Using mixins would require you to go back, make the `.Button` properties a mixin, and apply it to `.Button` and `.PromoButton`. To me, thats a big enough inconvenience.

We have a fork that should be ready for testing soon with extendable classes.

**Comment by davidtheclark** [comment]
Yeah, I've been thinking about it more and do think that the fact that there's not filesize difference means that extending real selectors still has a couple of uses while maybe placeholder selectors are unimportant --- the very stuff this plugin currently does :)

I just read http://www.smashingmagazine.com/2015/05/04/extending-in-sass-without-mess/ and it explains a lot of finer points about how selectors are extended in Sass -- if you're intereseted.

**Comment by timkelty** [comment]
@davidtheclark Yeah some of the stuff Sass does (outline in that article) is bonkers to me.

We're starting out by saying something is only extendable when there is an exact selector match.

So the _craziest_ you can get, would be: (not that I would ever suggest doing this)

```
.foo .bar {
  color: red;
}

.baz {
  @extend .foo .bar;
}

```

The one exception I think is pseudo-elements/classes. In the following case, I would think it be expected that the psuedos are also extended.

```
.Link {
  color: red;
}

.Link:hover {
  color: blue;
}

.OtherLink {
  @extend .Link;
}

```

**Comment by davidtheclark** [comment]
Cool. 

I'm wondering: Would your patch address https://github.com/davidtheclark/postcss-simple-extend/issues/2?

Also, @timkelty: If you're interested in working on a more complete `@extend` plugin, the @postcss/owners are open to it, especially if it approaches [the spec draft](http://tabatkins.github.io/specs/css-extend-rule/) closely enough that @MoOx might integrate it with cssnext. Something to think about.

Not that I wouldn't merge your change here, but I just mean you could get the coveted `postcss-extend` name if you want to take on the project :)

**Comment by davidtheclark** [comment]
Forget to reference: https://github.com/postcss/postcss/issues/321

**Comment by timkelty** [comment]
@davidtheclark our patch doesn't address #2.

We had it working if it was just jumping up one level of recursion, but beyond that it wouldn't work, so for now we're disabling any recursion.

**Comment by travco** [comment]
@davidtheclark As much as I love completely turning around what Tim said (just two days later) it looks like we're going to be able to address #2 (and by extention flip the accepted norm on its head with the ability to recursively extend things that haven't even been declared yet in some cases)

Basically, I got tired of going through the work to keep evaluations completely flat (non-recursive) and decided to put some work into seeing how far down the rabbit hole I can go with it. So far, it -appears- to be working without issues, but who knows, I might be sitting on the can of worms. I haven't had time to put together a rigorous test suite yet.

``` css
.bravo {
  @extend .charlie;
  color: blue;
  background: purple;
}
.charlie {
  @extend .delta;
  color: red;
  background: orange;
}
.delta {
  color: green;
  background: gray;
}
.echo {
  color: blue;
  background: purple;
}
.foxtrot {
  @extend .echo;
  color: red;
  background: orange;
}
.gulf {
  @extend .foxtrot;
  color: green;
  background: gray;
}
----------------Processing:----------------
.bravo {
  color: blue;
  background: purple;
}
.bravo, .charlie {
  color: red;
  background: orange;
}
.bravo, .charlie, .delta {
  color: green;
  background: gray;
}
.echo, .gulf, .foxtrot {
  color: blue;
  background: purple;
}
.gulf, .foxtrot {
  color: red;
  background: orange;
}
.gulf {
  color: green;
  background: gray;
}
```

**Comment by timkelty** [comment]
Hooray!

**Comment by davidtheclark** [comment]
Very cool

**Comment by davidtheclark** [comment]
Users who want these kinds of powers can now use https://github.com/travco/postcss-extend
