### ISSUE TITLE
Update README for the part about postcss-nested

### ISSUE THREAD

**Issue by wzxu** [davidtheclark/postcss-simple-extend#8]
It appears [the issue referred to was fixed on their side now](https://github.com/postcss/postcss-nested/issues/11). 

Besides, if I _do_ put simple-extend before nested as suggested, then something as simple as like `.foo { &:hover {...} }` will fail, because it gets extracted as `&:hover {...}` to the root level before nested could do its thing.

**Comment by davidtheclark** [comment]
Thanks for informing me that the issue was solved.
